#!python

#export LD_LIBRARY_PATH=/usr/local/lib

env = Environment()
env.Append(CPPPATH = ['../headers'], LIBS=['-lconfig', '-lcrypto', '-lssl'])

server = env.Object('server/server.c')
server_init = env.Object('server/server_init.c')

client = env.Object('client/client.c')
client_main = env.Object('client/client_main.c')


env.Program(target = ['server/server.out'], source = server + server_init)
env.Program(target = ['client/client.out'], source = client + client_main)
